show databases;
create database lab5;
use lab5;
show tables from lab5;
create table Patient (patientId varchar(15) not null,Name varchar(15),Age int, gender varchar(5), address varchar(20), disease varchar(10), doctorID varchar(15));
describe Patient;
alter table Patient add primary key (patientId);
alter table Patient modify gender char;
create table Doctor (DoctorId varchar(15) not null,Name varchar(15),Age int, gender char, address varchar(20));
alter table Doctor add primary key (DoctorId);
alter table Doctor add column DoctorWard varchar(15);
describe Doctor;
alter table Patient add foreign key (DoctorId) references Doctor(DoctorId);
describe Patient;
create table Lab (LabId varchar(15) not null,TestDate Date,TestAmount varchar(20),patientId varchar(15), DoctorId varchar(15));
alter table Lab add primary key (LabId);
alter table Lab add foreign key (DoctorId) references Doctor(DoctorId);
describe Lab;
alter table Lab add foreign key (patientId) references Patient(patientId);
describe Lab;
ALTER TABLE Lab CHANGE TestAmount Amount varchar(20);
describe Lab;
ALTER TABLE Lab MODIFY Amount double;
describe Lab;
alter table Lab add column LabNo varchar(10);
describe Lab;
create table HospitalRoom (RoomId varchar(15) not null,RoomAllocationDate Date,RoomType varchar(20),RoomStatus varchar(5));
alter table HospitalRoom add primary key (RoomId);
describe HospitalRoom;
create table PatientBill (BillId varchar(15) not null,BillDate Date,Amount varchar(20),patientId varchar(15));
alter table PatientBill add primary key (BillId);
describe PatientBill;
alter table PatientBill add foreign key (patientId) references Patient(patientId);
describe PatientBill;
ALTER TABLE HospitalRoom
  RENAME TO Room;
describe Room;